name: feola
favicon: null
layout_spectrum: 0.6662592233624309
typography_spectrum: 0.6404001619666815
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.5253123564179987
  lightness: 0.31846617069095373
  saturation: 0.8147450583055615
  rhythmicContrast: 0.9046583303716034
purpose: []
